name: pipeline back

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  deploy:
    name: Déploiement Backend
    runs-on: ubuntu-latest

    steps:
      - name: Check du cde
        uses: actions/checkout@v3

      - name: Installation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Installation des dépendances
        run: cd backend && npm install

      - name: Déploiement sur Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP }}
          publish-profile: ${{ secrets.AZURE_PARTIEL }}
          package: ./backend
      - name: Tests automatisés
        run: cd backend && npm test
