name: pipeline back

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v3

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Dépendances
        run: cd backend && npm install

      - name: Tests ok
        run: cd backend && npm test

  deploy:
    name: Backend
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check code
        uses: actions/checkout@v3

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Dépendances
        run: cd backend && npm install

      - name: Déploiement
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP }}
          publish-profile: ${{ secrets.AZURE_PARTIEL }}
          package: ./backend
