name: Deploy Frontend to Azure Blob Storage

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  deploy:
    name: Déploiement Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Upload vers Azure Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name frontazure \
              --destination '$web' \
              --source ./frontend \
              --overwrite
        env:
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
